include:
#  - services/proxy/docker-compose.yml
  - services/nextcloud/docker-compose.yml
#  - services/n8n/docker-compose.yml
#  - services/osm/docker-compose.yml

volumes:
  evidence:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/stacheldrath/Desktop/ComposeData

networks:
  stacheldrath-net:

